### ISSUE TITLE
Can't connect ... Fixed!

### ISSUE THREAD

**Issue by johns2947** [G6EJD/ESP8266-Autonomous-Graphing-Data-Logger#1]
Could not connect to the web server after successfully uploading the code file. In the code file is the comment: " then connect to http://192.168.4.1/ and follow instructions to make the WiFi connection"
Went to my browser and tried to connect to 192.168.4.1 but there was no such webpage.
Finally looked in my list of available wireless connections and saw a new "ESP8266_AP"
Disconnected from my wireless network and connected to this one. After connecting, nothing happened right away but after about 15 secs. a new browser window opened automatically to 192.168.4.1  !
On that page, I was able to set the ESP to use my wireless network's SSID and password, and Saved it.
Then disconnected from that wifi and reconnected to my own. Now went into my router's setup screens and found a new device on my network named ESP8266(something). Read the Details on that, and noted the IP address that was assigned to it.
Went back to my browser and typed in that address, and the ESP8266-Autonomous Graphing Data Logger opened!

ps. using NodeMCU on a MakerFocus ESP8266 board and Windows 10

**Comment by G6EJD** [comment]
Welcome to the world of the ESP8266 WiFiManager it can be a bit mind bending, but you describe is the process most people go through the first time through! Glad you got it sorted. I just happen to be using WiFiManager in my code. I think WiFiMulti is a better choice, less complex. Note that once you have used WiFiManager don't be surprised if that particular ESP8266 automatically connects to your Wifi even though you have not included code to do so! The crednetials for your WiFi are now stored in Flash on the ESP.
