### ISSUE TITLE
Cannot re-upload ... Fixed!

### ISSUE THREAD

**Issue by johns2947** [G6EJD/ESP8266-Autonomous-Graphing-Data-Logger#2]
Brand new ESP8266 on a MakerFocus board. Was able to upload some Blink examples ok, then uploaded this code, but couldn't figure out how to make it work.
Tried to re-upload, but got multiple "sync failed" errors. Was able to re-load the Blink examples, just not this code.
This board has a physical "Flash" push button. After researching some fixes for this problem on the Internet, I finally took a small alligator clip and used it to clamp down the Flash button.
Disconnected power from board, attached the alligator clip, re-attached power. Uploaded the code successfully, then powered down and removed the clip.
After figuring out how to access the Temp-Humidity page (see my other Issue), everything is working fine!
Now need to modify the code to display in Fahrenheit!

**Comment by G6EJD** [comment]
If it's a 'raw' ESP8266 with no UART and reset circuit there is a sequence of button pushes you need to do, usually flash hold and then reset

**Comment by johns2947** [comment]
Hello
It's this board:
https://www.amazon.com/gp/product/B01IK9GEQG/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

got it to reload by pressing and holding the Flash button 
thanks

**Comment by G6EJD** [comment]
That looks like a fairly standard board to me, have you tried choosing a different board type, it's laborious but try each one. You do-not need to press any of those buttons - ever unless you want to reset the chip. 

Also some boards have a maximum speed limit of 256000baud, so what I would do is to try programming it at 115200 which should work without issue, then gradually increase speed until it becomes unreliable, in fact the more I think about your error this is the issue your seeing.
