### ISSUE TITLE
How to display Fahrenheit?

### ISSUE THREAD

**Issue by johns2947** [G6EJD/ESP8266-Autonomous-Graphing-Data-Logger#3]
Working on this next. If you know how to modify the code, please advise, thanks

**Comment by G6EJD** [comment]
Find the lines that upload data to Google, like this, there are two: TempHumi and TempDew functions 
   webpage += "[" + String(i) + "," + String(float(sensor_data[i].temp)/10,1) + "," + String(float(sensor_data[i].humi)/1000,2) + "],"; 
Change to 👍     webpage += "[" + String(i) + "," + String(float((sensor_data[i].temp)*9/5+32)/10,1) + "," + String(float(sensor_data[i].humi)/1000,2) + "],"; 

Your best leaving the raw data in °C.

Next change this text Temperature Deg-C' to 'Temperature Deg-F'

**Comment by johns2947** [comment]
Well, not working yet. I understand the calculation you're doing, and typed it correctly (double and triple checked), but am getting a F temp of 56,4  ... C temp here right now is about 26, so F should be around 78, not 56.
Was able to modify the Dial settings to get a scale of -10 to 130, with major ticks up to 120, change the colors, and change most of the "C" to "F" in the titles and headers and footers. Just need to discover why it's not converting correctly.
maybe tomorrow.
thanks

**Comment by G6EJD** [comment]
I forgot that the raw data is x10 so add 320 needed not 32. Reason - to save storage for logging purposes, the readings are saved in a 16-bit integer, that saves 2-bytes per value, 4 overall. The reading say 26.12, is multiplied by 10 = 261.2 then converted to an integer = 261 and saved. 

When recalled we now need to convert to F, so 261x9/5+320=789 then the integer result is converted for printing to a floating point and /10 giving the result of 78.9

**Comment by johns2947** [comment]
Yes, that explains it. Before retiring for the night yesterday, I tried "hardcoding" it, replacing dht_temp/10,2 with just the number 78. I am mostly interested in the Dial display, and after uploading my change, the dial displayed a temp of 111 degrees F !
I knew then that I was not dealing with a straight linear conversion. The /10 was also a clue that I was not understanding the code.
Anyway, made the adjustment like you said and it's working perfectly now.
Thanks for following up and the quick responses!
![dial](https://user-images.githubusercontent.com/15602865/35477865-8a9a3e78-0382-11e8-99a7-4d6503acd218.jpg)

**Comment by G6EJD** [comment]
Happy to help, enjoy your coding.
