### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by johns2947** [G6EJD/ESP8266-Autonomous-Graphing-Data-Logger#4]
Looks like Yahoo mail won't let me respond to your emails, so feel free to delete this after you've read it.
Thanks for the Fahrenheit conversion ... I had thought to do something along those lines, but hadn't experimented with it yet.
As for my first "Issue" that I see is now closed, does that mean no one else will see it? I was hoping it might help the next person who has that problem.
Anyway, thanks for your help and your quick responses

**Comment by G6EJD** [comment]
No it remains for ever and a day :) 

I have not checked the WiFiManager recently but the author may have changed the setup from Access Point to Station mode such that you don't need to connect your wifi to the ESP8266, just type 192.168.4.1 and it accesses the setup page like any other web page/site.

You can clear the ESP credentials to try again (if you want :) ) with ESP.eraseConfig();
