### ISSUE TITLE
expected '(' before 'isnan'

### ISSUE THREAD

**Issue by whatsupskip** [G6EJD/ESP8266-Autonomous-Graphing-Data-Logger#5]
When I tried to compile the BME280 version I received the above error for the line
`if isnan(Calc_DewPoint(sensor_data[i].temp/10,sensor_data[i].humi/10)) dew_point = 0; else dew_point = Calc_DewPoint(sensor_data[i].temp/10,sensor_data[i].humi/10);`

Simply changing this to 
`if (isnan(Calc_DewPoint(sensor_data[i].temp/10,sensor_data[i].humi/10))) dew_point = 0; else dew_point = Calc_DewPoint(sensor_data[i].temp/10,sensor_data[i].humi/10);`
resolved the compile error. I don't yet know if this has created another problem.

**Comment by G6EJD** [comment]
It looks like in 2.4.2 syntax checking has been improved, previously OK.

Corrected now.

**Comment by asconint2019** [comment]
Hi,
  I am getting and error while compiling the code as as mentioned before please help.
 if (isnan(Calc_DewPoint(sensor_data[i].temp/10,sensor_data[i].humi/10)) dew_point = 0;  else dew_point = Calc_DewPoint(sensor_data[i].temp/10,sensor_data[i].humi/10);
even after including the  ( sign before isnan  compilation fails.

**Comment by G6EJD** [comment]
How did you copy the code?
There is almost certainly some hidden characters in your copy, usually the result of using a browser.  Delete and re-type the line or download the zip container.

**Comment by G6EJD** [comment]
I've just copied it (Select RAW then copy then paste into IDE), no issues found. Compiles correctly.

**Comment by asconint2019** [comment]
Thanks will try it now.

Regards,
Bilal

**Comment by asconint2019** [comment]
Hi,
   I followed your steps but unfortunately getting the same error again. i am attaching a screen shot here. 

![compilation-error-screen-shot](https://user-images.githubusercontent.com/53422068/97802888-fa323f80-1c5f-11eb-9697-f1bf87bc607f.jpg)

**Comment by G6EJD** [comment]
What version of the esp8266 plugin are you using?

**Comment by G6EJD** [comment]
Your not doing something right as I can see your source code in that screen shot is not the same as the correct version !
