### ISSUE TITLE
Problems with the SD libraries

### ISSUE THREAD

**Issue by whatsupskip** [G6EJD/ESP8266-Autonomous-Graphing-Data-Logger#6]
There seems to be a problem with SD libraries or the code.
"xtensa-lx106-elf-gcc: error: libraries\SD\SD.a: No such file or directory"

However the standard SD library is not compatible with the ESP8266. I tried having both libraries, but Arduino doesn't like that.

I have tried to determine the problem here, but I am hitting a brick wall. Any help would be appreciated.

**Comment by G6EJD** [comment]
I can't replicate this problem. This the library I'm using (in-built):

C:\Users\Admin\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.2\libraries\SD

I've just taken a Wemos D1 Mini ESP8266, added an SD-Card shield and the code works as expected. No issues to report.

I suggest you clear out your IDE or update to the latest versions 1.8.7 and ESP core 2.4.2

**Comment by whatsupskip** [comment]
WOW!

Thanks for the incredibly fast and helpful response!

**Comment by whatsupskip** [comment]
Is your board actually called "ESP8266 Dev"?

As I cleared out all the ESP8266 board libraries and reinstalled, but there is no such board listed.

I will try again later on a different computer. I will clear out all the Arduino from it first.

Thanks again for your help.

**Comment by G6EJD** [comment]
I presume you have solved your problem now?

**Comment by whatsupskip** [comment]
Thanks for your interest. No I haven't. I am sure the problem is at my end now. I have had to put it aside for the moment.

Thank you again for all your help.
