### ISSUE TITLE
Missing </script> in DHT11 project

### ISSUE THREAD

**Issue by danielw63** [G6EJD/ESP8266-Autonomous-Graphing-Data-Logger#7]
Hi G6EJD,
first of all thank you very much for your very well documented projects. 
Thanks to you I got Google Charts working for my ESP32 project.
In the beginning I just copied your HTML code and slightly adjusted some input data settings, but the chart didn´t show up
until I noticed that in line 237 of your project, there seems to be a `</script>` missing. 
When I added it, everything worked fine:
Before: `webpage += F("google.charts.load('current', {packages: ['corechart', 'line']});");`
After:  `webpage += F("google.charts.load('current', {packages: ['corechart', 'line']});</script>");`

**Comment by G6EJD** [comment]
Thank you, which version is faulty? Most look ok to me.

**Comment by danielw63** [comment]
I don`t know, if I'm wrong because I just just started with HTML this week, but in every version you made, you're loading the Google Charts like this: (line 237 in DHT11/DHT22 project for example)
`webpage += F("<script type=\"text/javascript\">");
 webpage += F("google.charts.load('current', {packages: ['corechart', 'line']});");`
In the following line, you're starting with a new `<script type...>`. 
So as I see it, there's always the `</script>` missing before this following line, isn't it?

**Comment by G6EJD** [comment]
https://developers.google.com/chart/interactive/docs/quick_start
I've just checked the Google API and this is the second time they have updated they access requirements in the last year, still evolving, I'll go through the code and correct the missing terminators, thank you.
